name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Executa diariamente à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a animação da cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: matson83
          outputs: |
            github-contribution-grid-snake.svg
            github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit e push do resultado
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Atualizando a animação da cobrinha"
          branch: output
